#!/bin/bash
# Quick Test Commands Reference

echo "═══════════════════════════════════════════════════════════════════════════"
echo "  NovaCart Dashboard — Test Quick Reference"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""

echo "📋 BACKEND TESTS (Python / pytest)"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "  Run all backend tests:"
echo "    cd backend && python -m pytest tests/ -v"
echo ""
echo "  Run input validation tests only:"
echo "    python -m pytest tests/test_input_validation.py -v"
echo ""
echo "  Run edge case tests only:"
echo "    python -m pytest tests/test_edge_cases.py -v"
echo ""
echo "  Run database query tests only:"
echo "    python -m pytest tests/test_database_queries.py -v"
echo ""
echo "  Run with coverage report:"
echo "    python -m pytest tests/ -v --cov=. --cov-report=html"
echo ""
echo "  Run single test:"
echo "    python -m pytest tests/test_input_validation.py::TestValidDateFormats::test_iso_date_range_returns_200 -v"
echo ""

echo "📋 FRONTEND TESTS (JavaScript / Vitest)"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "  Run all frontend tests:"
echo "    cd frontend && npm test"
echo ""
echo "  Run tests in watch mode:"
echo "    npm test -- --watch"
echo ""
echo "  Run specific test file:"
echo "    npm test tests/api.test.js"
echo ""

echo "🔧 SETUP & INSTALLATION"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "  Install backend dependencies:"
echo "    cd backend && python -m pip install -r requirements.txt"
echo ""
echo "  Install frontend dependencies:"
echo "    cd frontend && npm install"
echo ""
echo "  Run backend setup script:"
echo "    cd backend && python setup_tests.py"
echo ""

echo "📊 TEST COVERAGE"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "  Backend:"
echo "    • Input validation: 201 tests (date formats, injection, malformed, etc.)"
echo "    • Edge cases: 39+ tests (endpoints, empty data, NULL values, 404s)"
echo "    • Database queries: 32 tests (aggregates, JOINs, filters, LIMIT)"
echo "    • Total: 280+ tests"
echo ""
echo "  Frontend:"
echo "    • API response handling: 80+ tests (all endpoints, error cases)"
echo "    • Network error handling: 6 tests"
echo "    • Type validation: 4 tests"
echo ""

echo "✅ WHAT'S TESTED"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "  Backend Input Validation:"
echo "    ✓ Valid ISO 8601 dates"
echo "    ✓ Malformed dates (bad separators, out-of-range)"
echo "    ✓ SQL injection attempts"
echo "    ✓ Leap year edge cases"
echo "    ✓ Inverted date ranges"
echo "    ✓ Long string values"
echo "    ✓ HTTP method enforcement (GET-only)"
echo ""
echo "  Backend Edge Cases:"
echo "    ✓ Empty result sets"
echo "    ✓ NULL field values in queries"
echo "    ✓ Status filter (cancelled orders excluded)"
echo "    ✓ is_current filter (non-current customers excluded)"
echo "    ✓ Numeric field types"
echo "    ✓ Sorting and LIMIT clauses"
echo "    ✓ Health endpoint degradation"
echo "    ✓ 404 for unknown routes"
echo ""
echo "  Database Queries:"
echo "    ✓ Aggregate correctness (SUM, COUNT, MIN, MAX)"
echo "    ✓ JOIN correctness and orphan row handling"
echo "    ✓ BETWEEN inclusive semantics"
echo "    ✓ Monthly grouping and ordering"
echo "    ✓ Parameterised query injection prevention"
echo ""
echo "  Frontend Response Handling:"
echo "    ✓ Valid response shapes"
echo "    ✓ Empty lists"
echo "    ✓ NULL/undefined field handling"
echo "    ✓ Type mismatches (string vs number)"
echo "    ✓ Missing fields"
echo "    ✓ Network errors (4xx, 5xx)"
echo "    ✓ Malformed JSON"
echo ""

echo "📁 TEST FILES"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "  Backend:"
echo "    backend/tests/conftest.py                   ← Fixtures and seed data"
echo "    backend/tests/test_input_validation.py      ← Parameter validation"
echo "    backend/tests/test_edge_cases.py            ← Endpoint edge cases"
echo "    backend/tests/test_database_queries.py      ← SQL correctness"
echo "    backend/pytest.ini                          ← Pytest configuration"
echo ""
echo "  Frontend:"
echo "    frontend/tests/api.test.js                  ← API response tests"
echo ""
echo "  Documentation:"
echo "    TESTING.md                                  ← Full testing guide"
echo "    backend/setup_tests.py                      ← Test environment setup"
echo ""

echo "🚀 CI/CD INTEGRATION"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "  GitHub Actions workflow should:"
echo "    1. Install Python 3.11+"
echo "    2. Install backend requirements"
echo "    3. Run: pytest tests/ -v"
echo "    4. Install Node 18+"
echo "    5. Install frontend dependencies"
echo "    6. Run: npm test"
echo ""

echo "❓ TROUBLESHOOTING"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "  'ModuleNotFoundError: No module named fastapi'"
echo "    → cd backend && python -m pip install -r requirements.txt"
echo ""
echo "  Tests pass locally but fail in CI"
echo "    → Check Python version, environment variables, seed data"
echo ""
echo "  Single test fails:"
echo "    → Run with -vv for verbose output: pytest ... -vv"
echo ""
echo "  Frontend tests not found:"
echo "    → npm install --save-dev vitest"
echo "    → Ensure vite.config.js is configured"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
